#include <rpc/rpc.h>
#include "avg.h"
#include <stdio.h>

  /*
 * Adam Harms
 * 2/22/2022
 * description:
 * This is the server that responds to clients requests with an array of numbers. The program will take in an array with the first position
 * being the "sorting_option" (either 1 or 0) to specify whether the server uses an ascending or descending sort. After sorting it returns the array where the
 * client will print out the sorted version excluding the sorting option.
 *
 * Usage: run ./avg_svc to start the server. 
 */


/* run locally on 'server' called by a remote client. */
static double sum_avg;

// sorting algos for qsort to use
  int ascending_sort(const void * elem1, const void* elem2){

    // use qsort and make this the comparison function
    // https://stackoverflow.com/questions/1787996/c-library-function-to-perform-sort

    int f = *((double*)elem1);
    int s = *((double*)elem2);
    if (f > s) return  1;
    if (f < s) return -1;
    return 0;

  }
  int descending_sort(const void * elem1, const void* elem2){
    int f = *((double*)elem1);
    int s = *((double*)elem2);
    if (f < s) return  1;
    if (f > s) return -1;
    return 0;
  }
  

/* 
 * routine notice the _1 the version number 
 * notice the client handle, not sued here but needs to be 
 * a parameter 
 */
input_data * average_1(input_data *input, CLIENT *client) 
  {
  /* input is paramters were marshalled by genrated routine */
  /*  a pointer to a double, is set to begining of data array  */

  // this is where the server decides whether to use ascending or descending sort. Parses the 0 or 1 from the 1st input
  // talked with Dr. Ghosh in office hours and verified it is ok on 2/21.
  if(input->input_data.input_data_val[0] == 0){
    qsort(input->input_data.input_data_val, input->input_data.input_data_len, sizeof(double), ascending_sort);
  }

  else if(input->input_data.input_data_val[0] == 1) {//
    qsort(input->input_data.input_data_val, input->input_data.input_data_len, sizeof(double), descending_sort);
  }

 return (input);
}

/* 
 * server stub 'average_1_svc function handle called in avg_svc that was
 * generated by rpcgen 
 * FYI:
 *   result = (*local)((char *)&argument, rqstp);
 *   where local is (char *(*)(char *, struct svc_req *)) average_1_svc;
 */
 
input_data * average_1_svc(input_data *input, struct svc_req *svc) 
  {
  CLIENT *client;
  return( average_1( input, client) );
  }