/* written by client - calls client stub, xdr client, xdr xerver, server stub, server routine */ 

#include "avg.h"	/* header file generated by rpcgen */ 
#include <stdlib.h>
#include "stdbool.h"

 /*
 * Adam Harms
 * 2/22/2022
 * description:
 * This is the client which sends the initial array with a sorting option to the server for calculation of the new sorted array. 
 * These two programs together make a simple REST API where the client sends values, 
 * and the server responds with the result for the client to use. The client then prints out the sorted array skipping the sorting_option 
 *
 * Usage: run ./ravg 127.0.0.1 [array of numbers spaced excluding the brackets, with first position being sorting option] AFTER the server has started. 
 * Will receive response by server after this is ran. 
 */

/* local routine client */
/* prototype can be whatever you want */
void averageprog_1( char* host, int argc, char *argv[] )
{
   CLIENT *clnt; /* client handle, rpc.h included in avg.h from rpcgen */
   int i;
   double 	f, *dp, sort_option; //,  *result_1
   input_data *result_1;
   char 	*endptr;
   input_data  average_1_arg; /* input_data rpc struct */

   average_1_arg.input_data.input_data_val = (double*) malloc(MAXAVGSIZE*sizeof(double));

   /* pointer to double, beginning of input data */
   dp = average_1_arg.input_data.input_data_val;
   
   /* set number of items */

   average_1_arg.input_data.input_data_len = argc - 2;
   sort_option = strtod( argv[2], &endptr);
   for( i = 1; i <= (argc - 2); i++ )// i = 3 to skip the sorting identifier, i=0 is the local host,i=1 is with 0,
   {
	/* str to d ASCII string to floating point nubmer */
 	f = strtod( argv[i+1], &endptr);

        printf("value   = %e\n", f);
        *dp = f;
        dp++;
   }


   /*  clnt_create(host, program, version, protocol)
    * generic client create routine from rpc library * * program = AVERAGEPROG is the number 22855 
    * version = AVERAGEVERS is 1
    * transfer protocol 
    *
    * defined by application programmer in avg.x and  then
    * these definitions in turn are generated into avg.h 
    * udp is of-course the user datagram protocol 
    *
    * returns a client RPC handle
    */

   clnt = clnt_create( host, AVERAGEPROG, AVERAGEVERS, "udp" );

   /* check if error */
   if (clnt == NULL) 
   {
      /* 
       * rpc error library routine
       *  print a more descriptive error 
       */
   
      clnt_pcreateerror( host );
      exit(1);
   }


   /* now call average routine 'just' like a local routine 
    * but this will now go over network 
    * average_1 is definined in the client stub 
    * avg_clnt.c  that was generated by rpcgen
    * send in ptr to the parameters or args  in first field, and 
    * client handle in second field (created in clnt_create ) 
    * average_1 ultimately calls clnt_call() macro see man rpc
    *  than calls the remote routine associated with the client handle
    * so AVERAGEPROG, VERSION 
    */
   result_1 = average_1( &average_1_arg, clnt );

   if (result_1 == NULL) 
      {
      clnt_perror(clnt, "call failed:");
      }

   clnt_destroy( clnt );

   dp = result_1->input_data.input_data_val;
   bool skipped = 0;

   for( i = 0; i <= (argc - 3); i++ )
   {
      // this portion skips the sorting option 1 or 0, since there will only be 1 extra and after sort it doesnt matter it just skips printing and continues
      if(sort_option == 0 && result_1->input_data.input_data_val[i] == 0.000000 && skipped == 0) 
      {
         skipped = 1;
         dp++;
         continue;
      }
      if(sort_option==1 && result_1->input_data.input_data_val[i] == 1.000000 && skipped ==0){
         skipped = 1;
         dp++;
         continue;
      } 

        printf("sorted value   = %f\n", *dp);
        dp++;
   }
}


/* here is main */
main( int argc, char* argv[] )
{
   char *host;

   /* check correct syntax */
   if( argc < 3 )
   {
     	printf( "usage: %s server_host value ...\n", argv[0]); 
     	exit(1);
   }

   if( argc > MAXAVGSIZE + 2 )
   {
   	printf("Two many input values\n");
    	exit(2);
   }

   /* host name is in first parameter (after program name) */
   host = argv[1];
   averageprog_1( host, argc, argv);
}
