#include <rpc/rpc.h>
#include "avg.h"
#include <stdio.h>
#include <math.h>

  /*
 * Adam Harms
 * 2/22/2022
 * description:
 * This is the server that responds to clients requests with an array of numbers. The program will take in an array, sort it using the ascending sort
 * then calculate the median location using a stat formula with even and odd cases. Finally it finds the new median (or calculates it)
 * and returns that value to be printed to the client. 
 *
 * Usage: run ./avg_svc to start the server. use make to compile and make the progam usable.
 */

/* run locally on 'server' called by a remote client. */
static double sum_avg;

/* 
 * routine notice the _1 the version number 
 * notice the client handle, not sued here but needs to be 
 * a parameter 
 */

 int ascending_sort(const void * elem1, const void* elem2){

    // use qsort and make this the comparison function
    // https://stackoverflow.com/questions/1787996/c-library-function-to-perform-sort

    int f = *((double*)elem1);
    int s = *((double*)elem2);
    if (f > s) return  1;
    if (f < s) return -1;
    return 0;

  }
double * average_1(input_data *input, CLIENT *client) 
  {

  /* input is paramters were marshalled by genrated routine */
  /*  a pointer to a double, is set to begining of data array  */

  //sorts array so we can get location via L(m)
  qsort(input->input_data.input_data_val, input->input_data.input_data_len, sizeof(double), ascending_sort);
  double *dp = input->input_data.input_data_val;

  u_int i;
  sum_avg = 0;

  int med_loc = (input->input_data.input_data_len +1)/2;

  // if median location is odd, just get the median else calculate the one to the left and right add them and divide by 2
  if(input->input_data.input_data_len %2 ==1){
    sum_avg = input->input_data.input_data_val[med_loc-1];
  }

  else{
    double med_loc1 = ((double) input->input_data.input_data_len +1)/2;
    double left = (double) floor(med_loc1);
    double right = (double) ceil(med_loc1);
    int leftInt =0;
    int rightInt =0;
    leftInt = left-1;
    rightInt = right-1;
    sum_avg = (input->input_data.input_data_val[leftInt] + input->input_data.input_data_val[rightInt])/2;
  }
  return( &sum_avg );
}

/* 
 * server stub 'average_1_svc function handle called in avg_svc that was
 * generated by rpcgen 
 * FYI:
 *   result = (*local)((char *)&argument, rqstp);
 *   where local is (char *(*)(char *, struct svc_req *)) average_1_svc;
 */
 
double * average_1_svc(input_data *input, struct svc_req *svc) 
  {
  CLIENT *client;
  return( average_1( input, client) );
  }
